data<-read.table("household_power_consumption.txt",header = TRUE,sep=";",colClasses = c("character", "character", rep("numeric",7)),na.strings = "?")
workData<-data[data$Date=="1/2/2007"|data$Date=="2/2/2007",]
data_time<-paste(workData$Date,workData$Time)
workData$DateTime<-strptime(data_time,"%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(workData$DateTime,workData$Global_active_power,type='l',xlab="",ylab="Global Active Power(kolowatts)")
plot(workData$DateTime,workData$Voltage,type='l',xlab="datetime",ylab="Voltage")
plot(workData$DateTime,workData$Sub_metering_1,type='l',xlab="",ylab="Energy sub metering",col="black")
lines(workData$DateTime,workData$Sub_metering_2,col="red")
lines(workData$DateTime,workData$Sub_metering_3,col="blue")
legend("topright",col = c("black", "red", "blue"),legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lwd=1,lty=1,cex=0.5)
plot(workData$DateTime,workData$Global_reactive_power,type='l',xlab="datetime",ylab="Global_reactive_power")
dev.copy(device=png,filename='plot4.png',width=480,height=480)
dev.off()